name: macOS unit

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Unit tests on macOS Catalina
    runs-on: macos-latest
    strategy:
      matrix:
        float-precision: [2]

    steps:
      - name: install OpenMP library
        run: brew install libomp

      - uses: actions/checkout@v1

      - name: make build directory
        run: mkdir build_dir

      - name: cmake configure
        run: cmake .. -DTESTING:BOOL=ON -DPRECISION:STRING=${{matrix.float-precision}}
        working-directory: build_dir

      - name: cmake build
        run: cmake --build . --parallel 2 --target tests
        working-directory: build_dir

      - name: cmake test
        run: ctest -j2 --output-on-failure
        working-directory: build_dir
